---
apiVersion: v1
kind: Service
metadata:
  name:  donateyourbooks
  labels:
    app:  donateyourbooks
spec:
  type: NodePort
  selector:
    app:  donateyourbooks
  ports:
  - protocol: TCP
    port:  9090
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  donateyourbooks
spec:
  selector:
    matchLabels:
      app:  donateyourbooks
  replicas: 1
  template:
    metadata:
      labels:
        app:  donateyourbooks
    spec:
      containers:
      - name:  donateyourbooks
        image: narendrakareli/donateyourbooks:latest
        ports:
        - containerPort:  9090
        livenessProbe:
          httpGet:
            path: /health
            port:  9090
          initialDelaySeconds: 30
          timeoutSeconds: 1
